"""Add News and Category models

Revision ID: c358d7e5bc2c
Revises: 25f9280d7f67
Create Date: 2024-12-17 16:48:24.094979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c358d7e5bc2c'
down_revision: Union[str, None] = '25f9280d7f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
